/* BioVerseAR — quiz question bank (data-driven, keyed by TOPICS id).
 *
 * SOURCE OF TRUTH: research team + Ma’am Leah. Generated verbatim from the
 * approved "Quiz q&a" document: 7 topics × 3 difficulties × 10 questions = 210.
 * Points per difficulty: easy 5, medium 15, hard 30 (additive, no penalty).
 * Same set is used for both pre-test and post-test (learning-gain design).
 * `correct` is the 0-based index of the right option.
 *
 * Feedback phrases below are the approved generic sets (shown at random); per-
 * question explanations will be added when the next question set arrives.
 */
window.QUIZ_POINTS = { easy: 5, medium: 15, hard: 30 };

window.QUIZ_CORRECT_FEEDBACK = [
  "Excellent! You got it right!",
  "Great job! That's correct!",
  "Correct! Well done!",
  "Awesome work!",
  "Perfect answer!",
  "You nailed it!",
  "That's right! Keep it up!",
  "Fantastic! You understand the concept.",
  "Great thinking!",
  "Correct! You're doing great!",
  "Nice work!",
  "Brilliant! That's the correct answer.",
  "You got it!",
  "Excellent thinking!",
  "That's exactly right!",
  "Amazing! Keep going!",
  "Well done! You're on the right track.",
  "Correct! Your knowledge is growing.",
  "Great answer!",
  "Fantastic work!",
  "You understood it perfectly!",
  "Yes! That's correct!",
  "Impressive! Keep it going!",
  "Great choice!",
  "Correct! Nice reasoning!",
  "You're doing awesome!",
  "That's the one! Great job!",
  "Excellent work! Next question!",
  "You got this!",
  "Super! That's correct!",
  "Well played!",
  "Amazing answer!",
  "Great job! You know your science!",
  "Correct! Keep exploring!",
  "Fantastic thinking!",
  "You're on fire!",
  "Spot on!",
  "Excellent! You figured it out.",
  "Great work! Keep learning!",
  "That's correct! Nicely done.",
  "You made the right choice!",
  "Outstanding!",
  "Correct! You're mastering this topic.",
  "Great effort and correct answer!",
  "Yes! You got it right!",
  "Excellent choice!",
  "Fantastic! Your answer is correct.",
  "Nice! You understood the question.",
  "Great job! Keep the momentum going!",
  "Perfect! Ready for the next one?"
];

window.QUIZ_WRONG_FEEDBACK = [
  "Not quite! Try again next time.",
  "Almost! Keep learning!",
  "That's not the correct answer.",
  "Nice try! Don't give up.",
  "Not this time. Keep going!",
  "Incorrect, but you can learn from it!",
  "Give it another thought.",
  "Close! Review the concept and try again.",
  "Don't worry! Mistakes help us learn.",
  "Not quite right. Keep trying!",
  "Good attempt! Let's learn from this.",
  "That's incorrect. Keep practicing!",
  "Almost there! Try to remember the lesson.",
  "Not the answer we're looking for.",
  "Keep going! You've got more questions ahead.",
  "That's not quite it. Think carefully.",
  "Nice effort! Try to understand why.",
  "Incorrect this time. Don't give up!",
  "Keep practicing and you'll get it!",
  "Not quite! Review this topic.",
  "That's not correct, but every mistake teaches you something.",
  "Try again! Think about what you learned.",
  "Close one! Better luck on the next question.",
  "Not this one. Keep exploring!",
  "Good try! Check the lesson again.",
  "That's incorrect. You can do better!",
  "Almost! Think about the question again.",
  "Not quite right. Keep your focus!",
  "Don't be discouraged. Keep learning!",
  "Wrong answer, but you've got this!",
  "Take another look at the concept.",
  "Not quite! Remember what you studied.",
  "Keep trying! Practice makes progress.",
  "That's not the correct choice.",
  "Good attempt! Let's keep learning.",
  "Almost there! Don't give up!",
  "Not this time, but you can get the next one!",
  "Think carefully and try again.",
  "That's incorrect. Keep improving!",
  "A little off! Review the topic.",
  "Nice attempt! Learn from the mistake.",
  "Not quite! You've got this.",
  "Keep going! One mistake won't stop you.",
  "That's not it. Try to remember the key idea.",
  "Incorrect, but you're still learning!",
  "Almost! Pay close attention to the details.",
  "Not quite right. Give the next one your best shot!",
  "Good effort! Keep practicing.",
  "That's not the answer. Don't give up!",
  "Keep learning! You'll get the next one!"
];

// OPTIONAL per-question explanations, shown in the "See explanation" panel after a
// question is answered. The four below are SAMPLES (Animal Cells) to demonstrate the
// UI — the research team / Ma'am Leah will supply the real explanations. Keyed by
// question id; any question without an entry simply shows no explanation toggle.
window.QUIZ_EXPLANATIONS = {
  'ac-e1': "The cell is the smallest unit that can carry out all the processes of life. Tissues, organs, and organ systems are all built from cells.",
  'ac-e2': "The nucleus is the control centre of the cell — it holds the DNA and directs the cell's activities.",
  'ac-e4': "Mitochondria are the “powerhouse of the cell”: they release usable energy (ATP) from food through cellular respiration.",
  'ac-e7': "Ribosomes are the sites of protein synthesis — they read the cell's genetic instructions and build proteins."
};

window.QUIZZES = {
  // Animal Cells — 30 questions (10 easy, 10 medium, 10 hard)
  "animal-cells": {
    questions: [
      // EASY
      { id: "ac-e1", difficulty: "easy", correct: 2,
        q: "What is the basic unit of life?",
        options: ["Organ", "Tissue", "Cell", "Organ system"] },
      { id: "ac-e2", difficulty: "easy", correct: 0,
        q: "Which part of an animal cell controls the activities of the cell?",
        options: ["Nucleus", "Cytoplasm", "Cell membrane", "Mitochondrion"] },
      { id: "ac-e3", difficulty: "easy", correct: 1,
        q: "What is the main function of the cell membrane?",
        options: ["Produces energy", "Controls what enters and leaves the cell", "Stores genetic information", "Produces proteins"] },
      { id: "ac-e4", difficulty: "easy", correct: 1,
        q: "Which organelle produces energy for the cell?",
        options: ["Nucleus", "Mitochondrion", "Ribosome", "Lysosome"] },
      { id: "ac-e5", difficulty: "easy", correct: 0,
        q: "What is the jelly-like material inside a cell called?",
        options: ["Cytoplasm", "Cell wall", "Chlorophyll", "Nucleolus"] },
      { id: "ac-e6", difficulty: "easy", correct: 1,
        q: "Which structure contains the genetic material of an animal cell?",
        options: ["Cell membrane", "Nucleus", "Cytoplasm", "Vacuole"] },
      { id: "ac-e7", difficulty: "easy", correct: 0,
        q: "Which organelle makes proteins?",
        options: ["Ribosome", "Lysosome", "Mitochondrion", "Vacuole"] },
      { id: "ac-e8", difficulty: "easy", correct: 2,
        q: "Which of these is found in animal cells?",
        options: ["Chloroplast", "Cell wall", "Cell membrane", "Large central vacuole"] },
      { id: "ac-e9", difficulty: "easy", correct: 1,
        q: "What gives an animal cell its outer boundary?",
        options: ["Nucleus", "Cell membrane", "Cytoplasm", "Ribosome"] },
      { id: "ac-e10", difficulty: "easy", correct: 0,
        q: "Which organelle helps break down waste materials inside the cell?",
        options: ["Lysosome", "Nucleus", "Ribosome", "Chloroplast"] },
      // MEDIUM
      { id: "ac-m1", difficulty: "medium", correct: 2,
        q: "Which organelle is often called the \"powerhouse of the cell\"?",
        options: ["Ribosome", "Nucleus", "Mitochondrion", "Lysosome"] },
      { id: "ac-m2", difficulty: "medium", correct: 0,
        q: "What is the main function of ribosomes?",
        options: ["Producing proteins", "Storing water", "Controlling the cell", "Breaking down waste"] },
      { id: "ac-m3", difficulty: "medium", correct: 1,
        q: "Which statement correctly describes the nucleus?",
        options: ["It produces all the cell's energy", "It controls many cell activities and contains DNA", "It controls the movement of substances into the cell", "It breaks down waste materials"] },
      { id: "ac-m4", difficulty: "medium", correct: 1,
        q: "Why do animal cells need mitochondria?",
        options: ["To store DNA", "To produce usable energy", "To protect the cell", "To make the cell green"] },
      { id: "ac-m5", difficulty: "medium", correct: 1,
        q: "Which structure allows oxygen and nutrients to enter an animal cell while controlling other substances?",
        options: ["Nucleus", "Cell membrane", "Ribosome", "Lysosome"] },
      { id: "ac-m6", difficulty: "medium", correct: 0,
        q: "Which organelle receives proteins and other materials from the endoplasmic reticulum and helps prepare them for transport?",
        options: ["Golgi apparatus", "Nucleus", "Mitochondrion", "Lysosome"] },
      { id: "ac-m7", difficulty: "medium", correct: 2,
        q: "What is the main function of lysosomes?",
        options: ["Making DNA", "Producing oxygen", "Breaking down waste and damaged cell parts", "Producing proteins"] },
      { id: "ac-m8", difficulty: "medium", correct: 0,
        q: "Which structure is responsible for transporting materials within the cell?",
        options: ["Endoplasmic reticulum", "Nucleus", "Cell membrane", "Lysosome"] },
      { id: "ac-m9", difficulty: "medium", correct: 0,
        q: "What would most likely happen if an animal cell did not have a functioning cell membrane?",
        options: ["The cell would have difficulty controlling substances entering and leaving", "The cell would produce too much DNA", "The cell would immediately produce more proteins", "The cell would become a plant cell"] },
      { id: "ac-m10", difficulty: "medium", correct: 0,
        q: "Which organelles work together to make and transport proteins?",
        options: ["Ribosomes and endoplasmic reticulum", "Lysosomes and mitochondria", "Nucleus and lysosomes", "Vacuoles and mitochondria"] },
      // HARD
      { id: "ac-h1", difficulty: "hard", correct: 1,
        q: "A muscle cell requires a large amount of energy to function. Which organelle would likely be especially numerous in this cell?",
        options: ["Lysosomes", "Mitochondria", "Ribosomes", "Vacuoles"] },
      { id: "ac-h2", difficulty: "hard", correct: 0,
        q: "A cell has many ribosomes attached to its rough endoplasmic reticulum. What does this suggest about the cell?",
        options: ["It produces many proteins", "It stores large amounts of water", "It performs photosynthesis", "It does not contain DNA"] },
      { id: "ac-h3", difficulty: "hard", correct: 1,
        q: "A scientist observes a cell with a nucleus, mitochondria, ribosomes, and a cell membrane but no cell wall or chloroplasts. What type of cell is it most likely?",
        options: ["Plant cell", "Animal cell", "Bacterial cell", "Fungal cell"] },
      { id: "ac-h4", difficulty: "hard", correct: 0,
        q: "What would most likely happen to an animal cell if its mitochondria stopped working properly?",
        options: ["The cell would have less usable energy", "The cell would gain a cell wall", "The cell would produce more chloroplasts", "The cell would stop containing DNA"] },
      { id: "ac-h5", difficulty: "hard", correct: 0,
        q: "A cell needs to send a newly produced protein outside the cell. Which sequence best describes the pathway?",
        options: ["Ribosome → rough ER → Golgi apparatus → cell membrane", "Nucleus → lysosome → mitochondria → cell membrane", "Mitochondria → ribosome → nucleus → Golgi apparatus", "Cell membrane → nucleus → ribosome → lysosome"] },
      { id: "ac-h6", difficulty: "hard", correct: 0,
        q: "Why are cells in an organism different from one another even though they generally contain the same DNA?",
        options: ["Different cells use different sets of genes", "Different cells have completely different DNA", "Only some cells contain chromosomes", "Cells randomly change their DNA every day"] },
      { id: "ac-h7", difficulty: "hard", correct: 0,
        q: "An animal cell is placed in a solution with a much higher concentration of water outside the cell. What is most likely to happen?",
        options: ["Water moves into the cell, causing it to swell", "Water immediately leaves the cell", "The nucleus leaves the cell", "The cell begins photosynthesis"] },
      { id: "ac-h8", difficulty: "hard", correct: 0,
        q: "A cell has damaged proteins that need to be removed. Which organelle would be most directly involved in breaking down these unwanted materials?",
        options: ["Lysosome", "Ribosome", "Nucleus", "Mitochondrion"] },
      { id: "ac-h9", difficulty: "hard", correct: 0,
        q: "If the Golgi apparatus stopped functioning, which cellular process would be most affected?",
        options: ["Modifying, sorting, and packaging proteins for transport", "Copying DNA inside the nucleus", "Producing energy from food", "Controlling what enters the cell"] },
      { id: "ac-h10", difficulty: "hard", correct: 0,
        q: "A researcher compares two animal cells. Cell A has many mitochondria, while Cell B has fewer mitochondria. Which conclusion is most reasonable?",
        options: ["Cell A likely has higher energy requirements", "Cell B cannot contain DNA", "Cell A must be a plant cell", "Cell B cannot perform cellular respiration"] }
    ]
  },
  // Human Cells — 30 questions (10 easy, 10 medium, 10 hard)
  "human-cells": {
    questions: [
      // EASY
      { id: "hc-e1", difficulty: "easy", correct: 1,
        q: "What is the smallest basic unit that makes up the human body?",
        options: ["Organ", "Cell", "Tissue", "Organ system"] },
      { id: "hc-e2", difficulty: "easy", correct: 0,
        q: "Which part of a human cell contains DNA?",
        options: ["Nucleus", "Cytoplasm", "Cell membrane", "Ribosome"] },
      { id: "hc-e3", difficulty: "easy", correct: 0,
        q: "Which type of human cell carries oxygen around the body?",
        options: ["Red blood cell", "Nerve cell", "Muscle cell", "Bone cell"] },
      { id: "hc-e4", difficulty: "easy", correct: 1,
        q: "Which cells help protect the body from harmful germs?",
        options: ["Red blood cells", "White blood cells", "Muscle cells", "Bone cells"] },
      { id: "hc-e5", difficulty: "easy", correct: 0,
        q: "Which type of cell helps the body move?",
        options: ["Muscle cell", "Red blood cell", "Nerve cell", "Skin cell"] },
      { id: "hc-e6", difficulty: "easy", correct: 2,
        q: "Which cells send electrical signals throughout the body?",
        options: ["Bone cells", "Muscle cells", "Nerve cells", "Red blood cells"] },
      { id: "hc-e7", difficulty: "easy", correct: 1,
        q: "What is the main function of red blood cells?",
        options: ["Fight infections", "Carry oxygen", "Control movement", "Produce hormones"] },
      { id: "hc-e8", difficulty: "easy", correct: 0,
        q: "Which type of cell makes up much of the body's bones?",
        options: ["Bone cell", "Nerve cell", "Blood cell", "Muscle cell"] },
      { id: "hc-e9", difficulty: "easy", correct: 2,
        q: "What is the main function of muscle cells?",
        options: ["Carry oxygen", "Fight bacteria", "Allow the body to move", "Store genetic information"] },
      { id: "hc-e10", difficulty: "easy", correct: 1,
        q: "Which type of cell is mainly responsible for sending messages between the brain and other parts of the body?",
        options: ["Red blood cell", "Nerve cell", "Bone cell", "Skin cell"] },
      // MEDIUM
      { id: "hc-m1", difficulty: "medium", correct: 1,
        q: "Why are human cells considered specialized?",
        options: ["They all perform exactly the same function", "They have different structures and functions for specific jobs", "They do not contain DNA", "They only exist in the blood"] },
      { id: "hc-m2", difficulty: "medium", correct: 1,
        q: "Which type of cell is mainly responsible for carrying oxygen using hemoglobin?",
        options: ["White blood cell", "Red blood cell", "Nerve cell", "Muscle cell"] },
      { id: "hc-m3", difficulty: "medium", correct: 0,
        q: "Why do red blood cells have a shape that is thin in the middle?",
        options: ["It helps them carry and exchange gases efficiently", "It allows them to produce bones", "It helps them fight infections", "It allows them to send nerve signals"] },
      { id: "hc-m4", difficulty: "medium", correct: 1,
        q: "What is the main role of white blood cells?",
        options: ["Transport oxygen", "Fight infections and harmful organisms", "Contract muscles", "Carry electrical signals"] },
      { id: "hc-m5", difficulty: "medium", correct: 1,
        q: "Which cell structure controls what substances enter and leave the cell?",
        options: ["Nucleus", "Cell membrane", "Mitochondrion", "Ribosome"] },
      { id: "hc-m6", difficulty: "medium", correct: 0,
        q: "Why do muscle cells contain many mitochondria?",
        options: ["They need large amounts of energy for contraction", "They need to store more DNA", "They need to produce antibodies", "They need to carry oxygen"] },
      { id: "hc-m7", difficulty: "medium", correct: 1,
        q: "Which sequence shows the correct organization of the human body from simplest to most complex?",
        options: ["Organ → cell → tissue → organ system", "Cell → tissue → organ → organ system", "Tissue → cell → organ → organ system", "Cell → organ → tissue → organ system"] },
      { id: "hc-m8", difficulty: "medium", correct: 1,
        q: "Which type of tissue is mainly responsible for transmitting electrical signals?",
        options: ["Muscle tissue", "Nervous tissue", "Bone tissue", "Epithelial tissue"] },
      { id: "hc-m9", difficulty: "medium", correct: 0,
        q: "What happens when many similar cells work together to perform a particular function?",
        options: ["They form a tissue", "They form DNA", "They become a molecule", "They become an organ system immediately"] },
      { id: "hc-m10", difficulty: "medium", correct: 2,
        q: "Which combination correctly matches the cell type with its function?",
        options: ["Red blood cell — fighting infections", "White blood cell — carrying oxygen", "Muscle cell — producing movement", "Nerve cell — forming bones"] },
      // HARD
      { id: "hc-h1", difficulty: "hard", correct: 0,
        q: "A person exercises intensely and their muscle cells require more energy. Which change would help meet this increased demand?",
        options: ["Increased activity of mitochondria", "Decreased oxygen delivery", "Reduced blood flow", "Decreased cellular respiration"] },
      { id: "hc-h2", difficulty: "hard", correct: 0,
        q: "A red blood cell is damaged and can no longer carry enough oxygen. Which body function would be most directly affected?",
        options: ["Delivery of oxygen to body tissues", "Transmission of nerve signals", "Digestion of food", "Production of movement"] },
      { id: "hc-h3", difficulty: "hard", correct: 0,
        q: "Why is the loss of the nucleus useful for mature human red blood cells?",
        options: ["It provides more space for hemoglobin", "It allows them to produce more DNA", "It makes them able to divide faster", "It allows them to fight infections"] },
      { id: "hc-h4", difficulty: "hard", correct: 0,
        q: "A nerve cell is damaged and cannot properly transmit electrical signals. Which function would most likely be affected?",
        options: ["Communication between the brain and body", "Oxygen transport", "Bone formation", "Blood clotting"] },
      { id: "hc-h5", difficulty: "hard", correct: 0,
        q: "Why can a skin cell and a muscle cell have different functions even though they contain the same genetic information?",
        options: ["Different genes are active in different types of cells", "Muscle cells do not contain DNA", "Skin cells have no cell membrane", "Each cell type has completely different chromosomes"] },
      { id: "hc-h6", difficulty: "hard", correct: 0,
        q: "A person's white blood cells are unable to function properly. What would most likely happen?",
        options: ["The body would have greater difficulty fighting infections", "The person's muscles would stop producing energy", "Oxygen would no longer exist in the blood", "Bones would immediately become weaker"] },
      { id: "hc-h7", difficulty: "hard", correct: 0,
        q: "Which situation best demonstrates how specialized human cells work together?",
        options: ["Red blood cells carry oxygen while muscle cells use oxygen to help produce energy", "All human cells perform exactly the same job", "Nerve cells carry oxygen while red blood cells send nerve signals", "Bone cells digest food while stomach cells carry oxygen"] },
      { id: "hc-h8", difficulty: "hard", correct: 0,
        q: "A person's cells are unable to obtain enough oxygen. Which cellular process would be most directly affected?",
        options: ["Cellular respiration", "DNA storage", "Cell division only", "Protein storage"] },
      { id: "hc-h9", difficulty: "hard", correct: 0,
        q: "A mutation causes a group of cells to divide uncontrollably. Why can this be harmful to the human body?",
        options: ["The uncontrolled cells can form abnormal growths and interfere with normal tissues", "The cells immediately become red blood cells", "The cells stop containing DNA", "The cells permanently increase oxygen levels in the body"] },
      { id: "hc-h10", difficulty: "hard", correct: 1,
        q: "A scientist discovers that a particular human cell has many mitochondria, a long shape, and structures specialized for contraction. What is the cell most likely?",
        options: ["Red blood cell", "Muscle cell", "White blood cell", "Nerve cell"] }
    ]
  },
  // Life Sciences — 30 questions (10 easy, 10 medium, 10 hard)
  "life-sciences": {
    questions: [
      // EASY
      { id: "ls-e1", difficulty: "easy", correct: 1,
        q: "Which of the following is a characteristic of living things?",
        options: ["They never change", "They grow and develop", "They cannot reproduce", "They do not need energy"] },
      { id: "ls-e2", difficulty: "easy", correct: 0,
        q: "What do plants need to make their own food?",
        options: ["Sunlight, water, and carbon dioxide", "Soil, oxygen, and salt", "Meat, sunlight, and oxygen", "Water, sugar, and oxygen"] },
      { id: "ls-e3", difficulty: "easy", correct: 2,
        q: "Which organism makes its own food?",
        options: ["Lion", "Mushroom", "Grass", "Eagle"] },
      { id: "ls-e4", difficulty: "easy", correct: 1,
        q: "What do we call an organism that eats plants?",
        options: ["Carnivore", "Herbivore", "Decomposer", "Producer"] },
      { id: "ls-e5", difficulty: "easy", correct: 2,
        q: "Which organism breaks down dead plants and animals?",
        options: ["Producer", "Herbivore", "Decomposer", "Predator"] },
      { id: "ls-e6", difficulty: "easy", correct: 1,
        q: "What is a group of organisms of the same species living in the same area called?",
        options: ["Ecosystem", "Population", "Community", "Habitat"] },
      { id: "ls-e7", difficulty: "easy", correct: 0,
        q: "What is the natural home of an organism called?",
        options: ["Habitat", "Population", "Food chain", "Community"] },
      { id: "ls-e8", difficulty: "easy", correct: 2,
        q: "Which organism is an example of a predator?",
        options: ["Grass", "Rabbit", "Lion", "Algae"] },
      { id: "ls-e9", difficulty: "easy", correct: 0,
        q: "What do animals need to obtain energy from food?",
        options: ["Digestion", "Photosynthesis", "Evaporation", "Condensation"] },
      { id: "ls-e10", difficulty: "easy", correct: 2,
        q: "Which of the following is a living organism?",
        options: ["Rock", "Water", "Tree", "Air"] },
      // MEDIUM
      { id: "ls-m1", difficulty: "medium", correct: 1,
        q: "What is the main source of energy for most ecosystems?",
        options: ["Soil", "The Sun", "Water", "Wind"] },
      { id: "ls-m2", difficulty: "medium", correct: 0,
        q: "Which organisms are usually found at the beginning of a food chain?",
        options: ["Producers", "Carnivores", "Decomposers", "Predators"] },
      { id: "ls-m3", difficulty: "medium", correct: 0,
        q: "Consider this food chain: Grass → Grasshopper → Frog → Snake What would most likely happen to the frog population if the number of grasshoppers decreased significantly?",
        options: ["The frog population would likely decrease", "The frog population would immediately increase", "The frog population would become producers", "The frog population would not need food"] },
      { id: "ls-m4", difficulty: "medium", correct: 1,
        q: "What is the main role of decomposers in an ecosystem?",
        options: ["Produce sunlight", "Break down dead organisms and return nutrients to the environment", "Hunt other animals", "Produce oxygen from rocks"] },
      { id: "ls-m5", difficulty: "medium", correct: 2,
        q: "Which relationship benefits both organisms?",
        options: ["Predation", "Competition", "Mutualism", "Parasitism"] },
      { id: "ls-m6", difficulty: "medium", correct: 1,
        q: "What is biodiversity?",
        options: ["The number of rocks in an ecosystem", "The variety of living organisms in an area", "The amount of water in an ecosystem", "The temperature of an environment"] },
      { id: "ls-m7", difficulty: "medium", correct: 0,
        q: "Why are adaptations important to organisms?",
        options: ["They help organisms survive and reproduce in their environment", "They prevent organisms from needing food", "They allow organisms to stop growing", "They make every organism identical"] },
      { id: "ls-m8", difficulty: "medium", correct: 0,
        q: "Which example shows competition?",
        options: ["Two lions competing for the same food", "A bee collecting nectar from a flower", "A tick feeding on a dog", "A mushroom breaking down a dead tree"] },
      { id: "ls-m9", difficulty: "medium", correct: 2,
        q: "Which level of organization includes different populations living together in the same area?",
        options: ["Organism", "Population", "Community", "Cell"] },
      { id: "ls-m10", difficulty: "medium", correct: 2,
        q: "What happens to energy as it moves from one level of a food chain to another?",
        options: ["All energy is transferred", "More energy is created", "Some energy is lost, mainly as heat", "Energy disappears completely"] },
      // HARD
      { id: "ls-h1", difficulty: "hard", correct: 0,
        q: "A drought causes the amount of grass in an ecosystem to decrease greatly. Which effect would most likely occur first?",
        options: ["Herbivore populations may decrease because there is less food", "Carnivores immediately become producers", "Decomposers stop functioning completely", "The amount of sunlight decreases"] },
      { id: "ls-h2", difficulty: "hard", correct: 0,
        q: "Why can removing a predator from an ecosystem cause problems?",
        options: ["Its prey population may increase and consume too many resources", "Producers immediately disappear", "The Sun stops providing energy", "Decomposers stop breaking down matter"] },
      { id: "ls-h3", difficulty: "hard", correct: 0,
        q: "A population of insects becomes resistant to a pesticide over many generations. Which explanation best describes this change?",
        options: ["Some insects had traits that helped them survive, and those traits became more common over generations", "Every insect intentionally changed its body", "The pesticide taught insects how to resist it", "The insects stopped reproducing"] },
      { id: "ls-h4", difficulty: "hard", correct: 0,
        q: "Why can a decrease in biodiversity make an ecosystem less stable?",
        options: ["Fewer species may mean fewer alternative ways for the ecosystem to respond to environmental changes", "More species always cause ecosystems to collapse", "Biodiversity prevents organisms from reproducing", "Fewer species always increase available resources"] },
      { id: "ls-h5", difficulty: "hard", correct: 0,
        q: "Consider this food chain: Grass → Rabbit → Snake → Eagle If the rabbit population suddenly becomes very large, what is the most likely short-term effect on the ecosystem?",
        options: ["Grass may decrease because more rabbits are feeding on it", "Grass will immediately increase", "Eagles will become producers", "Snakes will stop eating rabbits"] },
      { id: "ls-h6", difficulty: "hard", correct: 0,
        q: "Which statement best explains why energy decreases at higher levels of a food chain?",
        options: ["Organisms use much of the energy they obtain for life processes, and some is released as heat", "Energy is destroyed when an animal eats another organism", "Producers absorb all energy from consumers", "Energy only exists in plants"] },
      { id: "ls-h7", difficulty: "hard", correct: 0,
        q: "Two species live in the same ecosystem and depend on the same limited food source. What is most likely to happen?",
        options: ["They may compete for the available food", "They will always help each other", "Both species will become producers", "Neither species will be affected"] },
      { id: "ls-h8", difficulty: "hard", correct: 0,
        q: "A forest is destroyed and replaced with buildings. Which change would most directly affect the organisms that lived there?",
        options: ["Loss of habitat and available resources", "Increase in Earth's rotation", "Increase in the Sun's energy", "Decrease in gravity"] },
      { id: "ls-h9", difficulty: "hard", correct: 0,
        q: "Why is reproduction important for the survival of a species?",
        options: ["It allows organisms to produce offspring and pass genetic information to the next generation", "It allows organisms to stop using energy", "It prevents organisms from adapting", "It eliminates competition between species"] },
      { id: "ls-h10", difficulty: "hard", correct: 2,
        q: "An ecosystem contains plants, insects, birds, fungi, soil, water, and sunlight. Which statement best describes this ecosystem?",
        options: ["Only the living organisms are part of the ecosystem", "Only the nonliving components are part of the ecosystem", "Both living and nonliving components interact within the ecosystem", "The plants are the only important organisms"] }
    ]
  },
  // Earth & Space Sciences — 30 questions (10 easy, 10 medium, 10 hard)
  "earth-space": {
    questions: [
      // EASY
      { id: "es-e1", difficulty: "easy", correct: 1,
        q: "Which planet do we live on?",
        options: ["Mars", "Earth", "Venus", "Jupiter"] },
      { id: "es-e2", difficulty: "easy", correct: 2,
        q: "What is the closest star to Earth?",
        options: ["Sirius", "Polaris", "The Sun", "Alpha Centauri"] },
      { id: "es-e3", difficulty: "easy", correct: 1,
        q: "What object orbits Earth?",
        options: ["Mars", "The Moon", "The Sun", "Venus"] },
      { id: "es-e4", difficulty: "easy", correct: 0,
        q: "What causes day and night on Earth?",
        options: ["Earth's rotation", "Earth's revolution around the Sun", "The Moon's rotation", "Changes in the Sun's size"] },
      { id: "es-e5", difficulty: "easy", correct: 1,
        q: "How long does Earth take to complete approximately one rotation?",
        options: ["12 hours", "24 hours", "30 days", "365 days"] },
      { id: "es-e6", difficulty: "easy", correct: 3,
        q: "How long does Earth take approximately to orbit the Sun once?",
        options: ["24 hours", "7 days", "30 days", "365 days"] },
      { id: "es-e7", difficulty: "easy", correct: 3,
        q: "Which layer of Earth do we live on?",
        options: ["Inner core", "Outer core", "Mantle", "Crust"] },
      { id: "es-e8", difficulty: "easy", correct: 1,
        q: "What is Earth's natural satellite?",
        options: ["The Sun", "The Moon", "Mars", "Venus"] },
      { id: "es-e9", difficulty: "easy", correct: 2,
        q: "Which force keeps planets in orbit around the Sun?",
        options: ["Friction", "Magnetism", "Gravity", "Electricity"] },
      { id: "es-e10", difficulty: "easy", correct: 1,
        q: "Which planet is known as the Red Planet?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"] },
      // MEDIUM
      { id: "es-m1", difficulty: "medium", correct: 1,
        q: "What causes Earth's seasons?",
        options: ["Earth's distance from the Sun changing greatly", "Earth's tilted axis as it revolves around the Sun", "The Moon changing shape", "The Sun becoming hotter and colder"] },
      { id: "es-m2", difficulty: "medium", correct: 2,
        q: "What causes the different phases of the Moon?",
        options: ["Earth's shadow always covering part of the Moon", "The Moon producing different amounts of light", "Our view of the Moon's sunlit portion changing as it orbits Earth", "Clouds covering the Moon"] },
      { id: "es-m3", difficulty: "medium", correct: 1,
        q: "What happens during a solar eclipse?",
        options: ["Earth moves between the Sun and Moon", "The Moon moves between the Sun and Earth", "The Sun moves between Earth and the Moon", "Mars blocks the Sun"] },
      { id: "es-m4", difficulty: "medium", correct: 1,
        q: "What happens during a lunar eclipse?",
        options: ["The Moon moves between Earth and the Sun", "Earth moves between the Sun and Moon", "The Sun moves between Earth and the Moon", "Venus blocks the Moon"] },
      { id: "es-m5", difficulty: "medium", correct: 0,
        q: "Which layer of Earth's atmosphere contains most of the weather we experience?",
        options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"] },
      { id: "es-m6", difficulty: "medium", correct: 2,
        q: "Which process describes water changing from liquid to gas?",
        options: ["Condensation", "Freezing", "Evaporation", "Melting"] },
      { id: "es-m7", difficulty: "medium", correct: 1,
        q: "What causes ocean tides mainly?",
        options: ["Earth's rotation alone", "The gravitational pull of the Moon and Sun", "Underwater volcanoes", "Ocean temperature"] },
      { id: "es-m8", difficulty: "medium", correct: 2,
        q: "Which type of rock forms when melted rock cools and hardens?",
        options: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"] },
      { id: "es-m9", difficulty: "medium", correct: 1,
        q: "Which type of rock forms from layers of sediments that become compacted and cemented?",
        options: ["Igneous", "Sedimentary", "Metamorphic", "Magma"] },
      { id: "es-m10", difficulty: "medium", correct: 1,
        q: "What is the movement of tectonic plates responsible for?",
        options: ["Only changes in weather", "Earthquakes, volcanoes, and mountain formation", "The phases of the Moon", "The Earth's rotation"] },
      // HARD
      { id: "es-h1", difficulty: "hard", correct: 1,
        q: "Why is it summer in one hemisphere while it is winter in the other?",
        options: ["One hemisphere is always much closer to the Sun", "Earth's axis is tilted, causing different hemispheres to receive different amounts of direct sunlight", "The Sun changes its temperature throughout the year", "The Moon blocks sunlight from one hemisphere"] },
      { id: "es-h2", difficulty: "hard", correct: 2,
        q: "If Earth's axis were not tilted, what would most likely happen?",
        options: ["Earth would stop rotating", "The Moon would disappear", "Seasonal changes would be much less pronounced", "Earth's orbit would stop"] },
      { id: "es-h3", difficulty: "hard", correct: 1,
        q: "Why does the Moon appear to shine even though it does not produce its own light?",
        options: ["It produces light through chemical reactions", "It reflects light from the Sun", "It receives light from Earth", "It creates light through rotation"] },
      { id: "es-h4", difficulty: "hard", correct: 0,
        q: "A student notices that the Moon rises at a different time each night. What is the main reason?",
        options: ["The Moon is moving in its orbit around Earth", "The Sun changes position around Earth", "Earth's rotation stops at night", "The Moon changes its size"] },
      { id: "es-h5", difficulty: "hard", correct: 0,
        q: "Why do we experience different amounts of daylight throughout the year?",
        options: ["Earth's axis is tilted as Earth travels around the Sun", "The Sun moves closer and farther from Earth every day", "Earth's rotation speed changes dramatically each season", "The Moon controls the length of daytime"] },
      { id: "es-h6", difficulty: "hard", correct: 0,
        q: "An earthquake occurs along a fault where two tectonic plates suddenly move. What causes the ground to shake?",
        options: ["Stored energy is suddenly released as the rocks move", "The Sun heats the rocks", "Ocean tides push the plates apart", "Earth's atmosphere becomes heavier"] },
      { id: "es-h7", difficulty: "hard", correct: 0,
        q: "Why are earthquakes and volcanoes common near some tectonic plate boundaries?",
        options: ["Plate movement can cause stress, melting, and movement of Earth's crust", "These areas receive more sunlight", "Gravity is weaker near plate boundaries", "The atmosphere is thinner there"] },
      { id: "es-h8", difficulty: "hard", correct: 2,
        q: "A rock is exposed to heat and pressure deep underground but does not completely melt. What type of rock can form?",
        options: ["Igneous", "Sedimentary", "Metamorphic", "Magmatic"] },
      { id: "es-h9", difficulty: "hard", correct: 0,
        q: "How does the water cycle help move water around Earth's systems?",
        options: ["Water changes between forms and moves through processes such as evaporation, condensation, and precipitation", "Water is permanently destroyed after evaporation", "Water only moves through oceans", "Water can only exist as a liquid"] },
      { id: "es-h10", difficulty: "hard", correct: 0,
        q: "Scientists observe that a planet takes much longer to orbit the Sun than Earth. Which factor could explain this difference?",
        options: ["The planet's orbit around the Sun is much larger", "The planet has no gravity", "The planet does not rotate", "The planet cannot reflect sunlight"] }
    ]
  },
  // Matter — 30 questions (10 easy, 10 medium, 10 hard)
  "matter": {
    questions: [
      // EASY
      { id: "mt-e1", difficulty: "easy", correct: 1,
        q: "What is matter?",
        options: ["Anything that produces light", "Anything that has mass and takes up space", "Anything that makes sound", "Anything that moves"] },
      { id: "mt-e2", difficulty: "easy", correct: 2,
        q: "Which of the following is matter?",
        options: ["Light", "Sound", "Air", "Heat"] },
      { id: "mt-e3", difficulty: "easy", correct: 0,
        q: "Which state of matter has a definite shape and definite volume?",
        options: ["Solid", "Liquid", "Gas", "Plasma"] },
      { id: "mt-e4", difficulty: "easy", correct: 1,
        q: "Which state of matter has a definite volume but takes the shape of its container?",
        options: ["Solid", "Liquid", "Gas", "Plasma"] },
      { id: "mt-e5", difficulty: "easy", correct: 2,
        q: "Which state of matter has neither a definite shape nor a definite volume?",
        options: ["Solid", "Liquid", "Gas", "Ice"] },
      { id: "mt-e6", difficulty: "easy", correct: 1,
        q: "What happens to ice when it is heated enough?",
        options: ["It freezes", "It melts", "It condenses", "It becomes heavier"] },
      { id: "mt-e7", difficulty: "easy", correct: 1,
        q: "What is water in its solid state called?",
        options: ["Steam", "Ice", "Vapor", "Gas"] },
      { id: "mt-e8", difficulty: "easy", correct: 2,
        q: "Which of the following is an example of a gas?",
        options: ["Water", "Ice", "Oxygen", "Rock"] },
      { id: "mt-e9", difficulty: "easy", correct: 0,
        q: "Which state of matter has particles that are packed closely together and mainly vibrate in place?",
        options: ["Solid", "Liquid", "Gas", "Vapor"] },
      { id: "mt-e10", difficulty: "easy", correct: 1,
        q: "What happens when water is placed in a freezer?",
        options: ["It evaporates", "It freezes", "It boils", "It melts"] },
      // MEDIUM
      { id: "mt-m1", difficulty: "medium", correct: 0,
        q: "What happens to particles when a solid is heated?",
        options: ["They move more quickly", "They stop moving", "They disappear", "They become smaller"] },
      { id: "mt-m2", difficulty: "medium", correct: 2,
        q: "Which change of state occurs when a liquid becomes a gas?",
        options: ["Freezing", "Condensation", "Evaporation", "Melting"] },
      { id: "mt-m3", difficulty: "medium", correct: 1,
        q: "Which change of state occurs when a gas becomes a liquid?",
        options: ["Evaporation", "Condensation", "Freezing", "Melting"] },
      { id: "mt-m4", difficulty: "medium", correct: 2,
        q: "Which change occurs when a solid changes directly into a gas?",
        options: ["Melting", "Freezing", "Sublimation", "Condensation"] },
      { id: "mt-m5", difficulty: "medium", correct: 2,
        q: "Which of the following is a physical change?",
        options: ["Burning wood", "Rusting iron", "Melting ice", "Cooking an egg"] },
      { id: "mt-m6", difficulty: "medium", correct: 3,
        q: "Which of the following is a chemical change?",
        options: ["Cutting paper", "Melting chocolate", "Breaking glass", "Burning wood"] },
      { id: "mt-m7", difficulty: "medium", correct: 1,
        q: "What is mass?",
        options: ["The amount of space an object takes up", "The amount of matter in an object", "The temperature of an object", "The force acting on an object"] },
      { id: "mt-m8", difficulty: "medium", correct: 1,
        q: "What is volume?",
        options: ["The amount of matter in an object", "The amount of space an object occupies", "The weight of an object", "The temperature of an object"] },
      { id: "mt-m9", difficulty: "medium", correct: 2,
        q: "Which statement about particles in a gas is correct?",
        options: ["They are tightly packed and only vibrate", "They are close together and cannot move", "They are far apart and move freely", "They do not move at all"] },
      { id: "mt-m10", difficulty: "medium", correct: 1,
        q: "A glass of cold water develops droplets on its outside. Where does the water most likely come from?",
        options: ["Water passing through the glass", "Water vapor in the air condensing on the cold surface", "The glass producing water", "The water inside evaporating through the glass"] },
      // HARD
      { id: "mt-h1", difficulty: "hard", correct: 1,
        q: "Why can gases be compressed more easily than solids?",
        options: ["Gas particles are much larger", "Gas particles have large spaces between them", "Gas particles have no mass", "Solid particles do not move"] },
      { id: "mt-h2", difficulty: "hard", correct: 0,
        q: "A sealed container of water is heated. What happens to the particles of water?",
        options: ["They gain energy and move faster", "They lose energy and stop moving", "Their mass disappears", "They become completely motionless"] },
      { id: "mt-h3", difficulty: "hard", correct: 2,
        q: "A student leaves a wet shirt outside on a warm, sunny day. After several hours, the shirt is dry. Which process is mainly responsible?",
        options: ["Condensation", "Freezing", "Evaporation", "Deposition"] },
      { id: "mt-h4", difficulty: "hard", correct: 0,
        q: "Why does increasing temperature generally cause particles to move faster?",
        options: ["Heating gives particles more kinetic energy", "Heating removes all energy from particles", "Heating makes particles disappear", "Temperature only affects the mass of particles"] },
      { id: "mt-h5", difficulty: "hard", correct: 1,
        q: "A substance changes from a liquid to a gas but remains the same substance chemically. What type of change has occurred?",
        options: ["Chemical change", "Physical change", "Nuclear change", "Biological change"] },
      { id: "mt-h6", difficulty: "hard", correct: 2,
        q: "Which observation provides the strongest evidence that a chemical change has occurred?",
        options: ["Ice changes into water", "Water changes into steam", "A new substance forms with different properties", "Paper is cut into smaller pieces"] },
      { id: "mt-h7", difficulty: "hard", correct: 1,
        q: "A student mixes salt into water until the salt can no longer be seen. What happened to the salt?",
        options: ["It was destroyed", "It dissolved and formed a solution", "It changed into a gas", "It became a new element"] },
      { id: "mt-h8", difficulty: "hard", correct: 0,
        q: "Two objects have the same volume, but Object A has more mass than Object B. Which object has the greater density?",
        options: ["Object A", "Object B", "They have the same density", "There is not enough information"] },
      { id: "mt-h9", difficulty: "hard", correct: 0,
        q: "A metal spoon is placed in a cup of hot water. After several minutes, the spoon becomes hot. What explains this?",
        options: ["Heat is transferred from the hot water to the spoon", "The spoon produces heat by itself", "The water loses all of its mass", "The spoon changes into a liquid"] },
      { id: "mt-h10", difficulty: "hard", correct: 1,
        q: "A student heats a block of ice until it becomes liquid water and then continues heating it until it becomes water vapor. Which sequence correctly describes the changes?",
        options: ["Freezing → condensation", "Melting → evaporation", "Condensation → freezing", "Sublimation → melting"] }
    ]
  },
  // Force & Motion — 30 questions (10 easy, 10 medium, 10 hard)
  "force-motion": {
    questions: [
      // EASY
      { id: "fm-e1", difficulty: "easy", correct: 1,
        q: "What is a force?",
        options: ["A type of energy", "A push or pull", "A type of matter", "A measurement of time"] },
      { id: "fm-e2", difficulty: "easy", correct: 0,
        q: "What is motion?",
        options: ["A change in an object's position over time", "The amount of matter in an object", "A type of energy", "The temperature of an object"] },
      { id: "fm-e3", difficulty: "easy", correct: 2,
        q: "What unit is commonly used to measure force?",
        options: ["Meter", "Kilogram", "Newton", "Second"] },
      { id: "fm-e4", difficulty: "easy", correct: 1,
        q: "Which force pulls objects toward Earth?",
        options: ["Friction", "Gravity", "Magnetism", "Air resistance"] },
      { id: "fm-e5", difficulty: "easy", correct: 1,
        q: "Which force slows down objects when two surfaces rub against each other?",
        options: ["Gravity", "Friction", "Magnetism", "Tension"] },
      { id: "fm-e6", difficulty: "easy", correct: 0,
        q: "What happens when you push a stationary box hard enough?",
        options: ["It may begin to move", "It loses its mass", "It disappears", "It becomes weightless"] },
      { id: "fm-e7", difficulty: "easy", correct: 1,
        q: "What is speed?",
        options: ["The amount of matter in an object", "How fast an object moves", "The force pulling an object downward", "The size of an object"] },
      { id: "fm-e8", difficulty: "easy", correct: 0,
        q: "Which of the following is an example of a force?",
        options: ["Gravity", "Temperature", "Volume", "Time"] },
      { id: "fm-e9", difficulty: "easy", correct: 0,
        q: "What happens when you kick a soccer ball?",
        options: ["Your foot applies a force to the ball", "The ball loses its mass", "The ball stops experiencing gravity", "The ball becomes a different substance"] },
      { id: "fm-e10", difficulty: "easy", correct: 2,
        q: "Which object is moving?",
        options: ["A parked car", "A book on a table", "A rolling ball", "A chair in a classroom"] },
      // MEDIUM
      { id: "fm-m1", difficulty: "medium", correct: 1,
        q: "A car travels 100 meters in 10 seconds. What is its average speed?",
        options: ["5 m/s", "10 m/s", "50 m/s", "100 m/s"] },
      { id: "fm-m2", difficulty: "medium", correct: 0,
        q: "Two forces act on a box. One pushes it with 20 N to the right, while another pushes with 5 N to the left. What is the net force?",
        options: ["15 N to the right", "15 N to the left", "25 N to the right", "25 N to the left"] },
      { id: "fm-m3", difficulty: "medium", correct: 1,
        q: "What happens when balanced forces act on an object that is at rest?",
        options: ["It begins accelerating", "It remains at rest", "It moves backward", "It becomes weightless"] },
      { id: "fm-m4", difficulty: "medium", correct: 0,
        q: "What happens when unbalanced forces act on an object?",
        options: ["Its motion can change", "Its mass disappears", "It always stops moving", "Its temperature becomes zero"] },
      { id: "fm-m5", difficulty: "medium", correct: 1,
        q: "A cyclist increases their speed from 5 m/s to 10 m/s. What has happened to the cyclist's motion?",
        options: ["The cyclist has slowed down", "The cyclist has accelerated", "The cyclist has stopped", "The cyclist has changed direction only"] },
      { id: "fm-m6", difficulty: "medium", correct: 0,
        q: "Which force opposes the motion of a moving bicycle's tires against the road?",
        options: ["Friction", "Gravity", "Magnetic force", "Buoyant force"] },
      { id: "fm-m7", difficulty: "medium", correct: 1,
        q: "Why does a ball eventually stop rolling across the floor?",
        options: ["Gravity disappears", "Friction acts against its motion", "Its mass decreases", "The ball runs out of force"] },
      { id: "fm-m8", difficulty: "medium", correct: 2,
        q: "A person pushes a wall with 50 N, but the wall does not move. What is the best explanation?",
        options: ["No force was applied", "The wall has no mass", "The forces acting on the wall are balanced", "Gravity is not acting on the wall"] },
      { id: "fm-m9", difficulty: "medium", correct: 2,
        q: "Which situation demonstrates acceleration?",
        options: ["A car traveling at a constant speed in a straight line", "A parked bicycle", "A car increasing its speed", "A book resting on a desk"] },
      { id: "fm-m10", difficulty: "medium", correct: 1,
        q: "A runner travels 200 meters in 40 seconds. What is the runner's average speed?",
        options: ["4 m/s", "5 m/s", "8 m/s", "10 m/s"] },
      // HARD
      { id: "fm-h1", difficulty: "hard", correct: 0,
        q: "A box is pushed with 40 N to the right and 25 N to the left. What is the net force?",
        options: ["15 N to the right", "15 N to the left", "65 N to the right", "65 N to the left"] },
      { id: "fm-h2", difficulty: "hard", correct: 1,
        q: "A car travels 300 meters in 20 seconds. What is its average speed?",
        options: ["10 m/s", "15 m/s", "20 m/s", "30 m/s"] },
      { id: "fm-h3", difficulty: "hard", correct: 1,
        q: "Two identical balls are pushed with different forces. Ball A receives 10 N while Ball B receives 20 N. Assuming other conditions are the same, which ball will have greater acceleration?",
        options: ["Ball A", "Ball B", "Both will have the same acceleration", "Neither will accelerate"] },
      { id: "fm-h4", difficulty: "hard", correct: 0,
        q: "A moving car suddenly brakes. What force mainly causes the car to slow down?",
        options: ["Friction", "Gravity", "Magnetism", "Buoyancy"] },
      { id: "fm-h5", difficulty: "hard", correct: 0,
        q: "A passenger moves forward when a moving bus suddenly stops. Which concept best explains this?",
        options: ["Inertia", "Gravity", "Magnetism", "Buoyancy"] },
      { id: "fm-h6", difficulty: "hard", correct: 1,
        q: "A student pushes a 10 kg box with a net force of 30 N. What is the box's acceleration? Formula: acceleration = force ÷ mass",
        options: ["2 m/s²", "3 m/s²", "10 m/s²", "30 m/s²"] },
      { id: "fm-h7", difficulty: "hard", correct: 2,
        q: "A cyclist travels at 8 m/s for 15 seconds. Approximately how far does the cyclist travel? Formula: distance = speed × time",
        options: ["23 m", "60 m", "120 m", "150 m"] },
      { id: "fm-h8", difficulty: "hard", correct: 1,
        q: "A box is pushed with 50 N to the right while friction acts with 50 N to the left. What will happen to the box if it is already moving?",
        options: ["It must immediately stop", "It will continue moving at constant velocity", "It will accelerate to the right", "It will accelerate to the left"] },
      { id: "fm-h9", difficulty: "hard", correct: 1,
        q: "A 5 kg object experiences a net force of 20 N. What is its acceleration? Formula: acceleration = force ÷ mass",
        options: ["2 m/s²", "4 m/s²", "5 m/s²", "25 m/s²"] },
      { id: "fm-h10", difficulty: "hard", correct: 0,
        q: "A student pushes two boxes with the same force. Box A has a mass of 5 kg, while Box B has a mass of 10 kg. Which statement is correct?",
        options: ["Box A will have greater acceleration", "Box B will have greater acceleration", "Both boxes will have the same acceleration", "Neither box will move"] }
    ]
  },
  // Energy — 30 questions (10 easy, 10 medium, 10 hard)
  "energy": {
    questions: [
      // EASY
      { id: "en-e1", difficulty: "easy", correct: 0,
        q: "What is energy?",
        options: ["The ability to cause change or do work", "The amount of matter in an object", "The space occupied by an object", "A type of force"] },
      { id: "en-e2", difficulty: "easy", correct: 2,
        q: "Which object has kinetic energy?",
        options: ["A parked car", "A book on a table", "A rolling ball", "A rock sitting on the ground"] },
      { id: "en-e3", difficulty: "easy", correct: 1,
        q: "What type of energy does a moving object have?",
        options: ["Potential energy", "Kinetic energy", "Chemical energy", "Nuclear energy"] },
      { id: "en-e4", difficulty: "easy", correct: 1,
        q: "What type of energy is stored in a stretched rubber band?",
        options: ["Kinetic energy", "Potential energy", "Sound energy", "Light energy"] },
      { id: "en-e5", difficulty: "easy", correct: 2,
        q: "Which is the main source of energy for most life on Earth?",
        options: ["Moon", "Wind", "Sun", "Soil"] },
      { id: "en-e6", difficulty: "easy", correct: 1,
        q: "Which form of energy allows us to see objects?",
        options: ["Sound energy", "Light energy", "Chemical energy", "Mechanical energy"] },
      { id: "en-e7", difficulty: "easy", correct: 0,
        q: "Which type of energy is associated with the movement of an object?",
        options: ["Kinetic energy", "Potential energy", "Chemical energy", "Thermal energy"] },
      { id: "en-e8", difficulty: "easy", correct: 0,
        q: "What type of energy is stored in food?",
        options: ["Chemical energy", "Sound energy", "Light energy", "Mechanical energy"] },
      { id: "en-e9", difficulty: "easy", correct: 0,
        q: "Which device changes electrical energy into light energy?",
        options: ["Light bulb", "Fan", "Speaker", "Battery"] },
      { id: "en-e10", difficulty: "easy", correct: 1,
        q: "Which type of energy can be felt as warmth?",
        options: ["Sound energy", "Thermal energy", "Light energy", "Chemical energy"] },
      // MEDIUM
      { id: "en-m1", difficulty: "medium", correct: 1,
        q: "A ball is held at the top of a hill. What type of energy does it have because of its position?",
        options: ["Kinetic energy", "Potential energy", "Sound energy", "Electrical energy"] },
      { id: "en-m2", difficulty: "medium", correct: 0,
        q: "What happens to the potential energy of a ball as it falls toward the ground?",
        options: ["It generally decreases", "It increases continuously", "It disappears completely", "It becomes chemical energy"] },
      { id: "en-m3", difficulty: "medium", correct: 0,
        q: "As the ball in Question 12 falls, what happens to its kinetic energy?",
        options: ["It generally increases", "It decreases to zero immediately", "It stays exactly the same", "It changes into chemical energy"] },
      { id: "en-m4", difficulty: "medium", correct: 0,
        q: "Which energy transformation occurs when a battery powers a flashlight?",
        options: ["Chemical → electrical → light", "Light → chemical → electrical", "Thermal → sound → chemical", "Mechanical → light → chemical"] },
      { id: "en-m5", difficulty: "medium", correct: 0,
        q: "Which energy transformation occurs when a person eats food and then runs?",
        options: ["Chemical → mechanical", "Light → chemical", "Sound → electrical", "Thermal → light"] },
      { id: "en-m6", difficulty: "medium", correct: 0,
        q: "What happens to energy when a moving bicycle slows down because of friction?",
        options: ["Some kinetic energy is transformed into thermal energy", "All energy disappears", "Kinetic energy becomes mass", "Energy stops existing"] },
      { id: "en-m7", difficulty: "medium", correct: 2,
        q: "Which object has the greatest kinetic energy if all objects have the same mass?",
        options: ["A car moving at 5 m/s", "A car moving at 10 m/s", "A car moving at 15 m/s", "A parked car"] },
      { id: "en-m8", difficulty: "medium", correct: 0,
        q: "Which form of energy is produced when you strike a drum?",
        options: ["Sound energy", "Chemical energy", "Nuclear energy", "Gravitational energy"] },
      { id: "en-m9", difficulty: "medium", correct: 2,
        q: "Which energy source is renewable?",
        options: ["Coal", "Oil", "Solar energy", "Natural gas"] },
      { id: "en-m10", difficulty: "medium", correct: 0,
        q: "Which situation demonstrates energy being transferred from one object to another?",
        options: ["A hot spoon warms your hand", "A rock sitting on the ground", "A closed book on a desk", "A parked bicycle"] },
      // HARD
      { id: "en-h1", difficulty: "hard", correct: 1,
        q: "A roller coaster starts at the top of a hill and begins moving downward. Which energy transformation mainly occurs?",
        options: ["Kinetic energy → potential energy", "Potential energy → kinetic energy", "Chemical energy → nuclear energy", "Sound energy → chemical energy"] },
      { id: "en-h2", difficulty: "hard", correct: 1,
        q: "Two identical balls are moving at different speeds. Ball A travels at 5 m/s while Ball B travels at 10 m/s. Which ball has more kinetic energy?",
        options: ["Ball A", "Ball B", "Both have the same kinetic energy", "Neither has kinetic energy"] },
      { id: "en-h3", difficulty: "hard", correct: 0,
        q: "Why does a moving object generally have more kinetic energy when it moves faster?",
        options: ["Faster motion means the object has greater kinetic energy", "Faster objects have less mass", "Faster objects have no potential energy", "Speed removes friction completely"] },
      { id: "en-h4", difficulty: "hard", correct: 0,
        q: "A flashlight is turned on using a battery. Which sequence best represents the energy transformations?",
        options: ["Chemical → electrical → light and thermal", "Electrical → chemical → sound", "Thermal → chemical → light", "Mechanical → electrical → chemical"] },
      { id: "en-h5", difficulty: "hard", correct: 0,
        q: "A student lifts a 5 kg backpack from the floor onto a table. What happens to the backpack's gravitational potential energy?",
        options: ["It increases", "It decreases", "It becomes zero", "It remains exactly the same"] },
      { id: "en-h6", difficulty: "hard", correct: 0,
        q: "A pendulum swings back and forth. At which point does it generally have the greatest gravitational potential energy?",
        options: ["At its highest point", "At its lowest point", "Halfway through its motion only", "When it stops permanently"] },
      { id: "en-h7", difficulty: "hard", correct: 0,
        q: "Why does a pendulum eventually stop swinging in a real environment?",
        options: ["Some of its mechanical energy is transferred to the surroundings, mainly through friction and air resistance", "Its energy is completely destroyed", "Gravity disappears", "The pendulum loses all of its mass"] },
      { id: "en-h8", difficulty: "hard", correct: 0,
        q: "A solar panel is used to power a small motor. Which energy transformation is taking place?",
        options: ["Light → electrical → mechanical", "Chemical → light → electrical", "Mechanical → thermal → light", "Sound → chemical → electrical"] },
      { id: "en-h9", difficulty: "hard", correct: 0,
        q: "A student claims, \"When a moving car stops, its kinetic energy disappears.\" Which statement best corrects the claim?",
        options: ["The energy is transferred or transformed, such as into thermal energy through friction", "Energy disappears whenever an object stops", "The energy becomes matter", "The car creates new energy when it stops"] },
      { id: "en-h10", difficulty: "hard", correct: 0,
        q: "A roller coaster starts from rest at the top of a hill, travels down, and then climbs another hill. Ignoring friction, which statement best describes its energy?",
        options: ["Its total mechanical energy remains approximately constant while potential and kinetic energy change into each other", "Its total energy disappears as it moves", "Its kinetic energy always remains zero", "Its potential energy continuously increases throughout the entire ride"] }
    ]
  }
};
